// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Merbla.IPhone {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UILabel __mt_webServiceOutputLabel;
		
		private MonoTouch.UIKit.UILabel __mt_dragWindowOutputLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("webServiceOutputLabel")]
		private MonoTouch.UIKit.UILabel webServiceOutputLabel {
			get {
				this.__mt_webServiceOutputLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("webServiceOutputLabel")));
				return this.__mt_webServiceOutputLabel;
			}
			set {
				this.__mt_webServiceOutputLabel = value;
				this.SetNativeField("webServiceOutputLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("dragWindowOutputLabel")]
		private MonoTouch.UIKit.UILabel dragWindowOutputLabel {
			get {
				this.__mt_dragWindowOutputLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("dragWindowOutputLabel")));
				return this.__mt_dragWindowOutputLabel;
			}
			set {
				this.__mt_dragWindowOutputLabel = value;
				this.SetNativeField("dragWindowOutputLabel", value);
			}
		}
	}
}
